
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cesia Zamora
 */
public class Convertidor_Monedas extends javax.swing.JFrame {

    /**
     * Creates new form Convertidor_Monedas
     */
    public Convertidor_Monedas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        convertido = new javax.swing.JComboBox<>();
        convertir = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonConvertir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAbrir = new javax.swing.JMenu();
        Abri_con = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuBorrar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Convertidor de Monedas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Convertir de:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        convertido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar estadounidense", "Euro", "Peso Mexicano", "Lempira", "Quetzal" }));
        jPanel3.add(convertido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 159, 36));

        convertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar estadounidense", "Euro", "Peso Mexicano", "Lempira", "Quetzal" }));
        jPanel3.add(convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 159, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("a");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 10, -1));

        Resultado.setEnabled(false);
        jPanel3.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 170, 30));
        jPanel3.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Resultado:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cantidad:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 610, 163));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonConvertir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jButtonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 280, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        jMenuAbrir.setText("Abrir");

        Abri_con.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Abri_con.setText("Convertidor de Monedas");
        Abri_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abri_conActionPerformed(evt);
            }
        });
        jMenuAbrir.add(Abri_con);

        jMenuBar1.add(jMenuAbrir);

        jMenuOpciones.setText("Opciones");

        jMenuBorrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBorrar.setText("Borrar datos");
        jMenuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBorrarActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuBorrar);

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuSalir);

        jMenuBar1.add(jMenuOpciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Abri_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abri_conActionPerformed
        jPanel1.setVisible(true);
        jMenuOpciones.setEnabled(true);
        jMenuAbrir.setEnabled(false);
    }//GEN-LAST:event_Abri_conActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanel1.setVisible(false);
        jMenuOpciones.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        if(Cantidad.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Ingrese la cantidad a convertir");
                    else{
            int cantidad=0;
            cantidad = Integer.parseInt(Cantidad.getText());
            if(convertir.getSelectedIndex()==0 && convertido.getSelectedIndex()==0)
            Resultado.setText(String.valueOf(cantidad*1));
            if(convertir.getSelectedIndex()==0 && convertido.getSelectedIndex()==1)
            Resultado.setText(String.valueOf(cantidad*0.8844));
            if(convertir.getSelectedIndex()==0 && convertido.getSelectedIndex()==2)
            Resultado.setText(String.valueOf(cantidad*19.09));
            if(convertir.getSelectedIndex()==0 && convertido.getSelectedIndex()==3)
            Resultado.setText(String.valueOf(cantidad*24.52));
            if(convertir.getSelectedIndex()==0 && convertido.getSelectedIndex()==4)
            Resultado.setText(String.valueOf(cantidad*7.68));
            
            if(convertir.getSelectedIndex()==1 && convertido.getSelectedIndex()==0)
            Resultado.setText(String.valueOf(cantidad*1.13));
            if(convertir.getSelectedIndex()==1 && convertido.getSelectedIndex()==1)
            Resultado.setText(String.valueOf(cantidad*1));
            if(convertir.getSelectedIndex()==1 && convertido.getSelectedIndex()==2)
            Resultado.setText(String.valueOf(cantidad*21.59));
            if(convertir.getSelectedIndex()==1 && convertido.getSelectedIndex()==3)
            Resultado.setText(String.valueOf(cantidad*27.72));
            if(convertir.getSelectedIndex()==1 && convertido.getSelectedIndex()==4)
            Resultado.setText(String.valueOf(cantidad*8.68));
            
            if(convertir.getSelectedIndex()==2 && convertido.getSelectedIndex()==0)
            Resultado.setText(String.valueOf(cantidad*0.0524));
            if(convertir.getSelectedIndex()==2 && convertido.getSelectedIndex()==1)
            Resultado.setText(String.valueOf(cantidad*0.0463));
            if(convertir.getSelectedIndex()==2 && convertido.getSelectedIndex()==2)
            Resultado.setText(String.valueOf(cantidad*1));
            if(convertir.getSelectedIndex()==2 && convertido.getSelectedIndex()==3)
            Resultado.setText(String.valueOf(cantidad*1.28));
            if(convertir.getSelectedIndex()==2 && convertido.getSelectedIndex()==4)
            Resultado.setText(String.valueOf(cantidad*0.40));
            
            if(convertir.getSelectedIndex()==3 && convertido.getSelectedIndex()==0)
            Resultado.setText(String.valueOf(cantidad*0.0408));
            if(convertir.getSelectedIndex()==3 && convertido.getSelectedIndex()==1)
            Resultado.setText(String.valueOf(cantidad*0.0361));
            if(convertir.getSelectedIndex()==3 && convertido.getSelectedIndex()==2)
            Resultado.setText(String.valueOf(cantidad*0.78));
            if(convertir.getSelectedIndex()==3 && convertido.getSelectedIndex()==3)
            Resultado.setText(String.valueOf(cantidad*1));
            if(convertir.getSelectedIndex()==3 && convertido.getSelectedIndex()==4)
            Resultado.setText(String.valueOf(cantidad*0.31));
            
            if(convertir.getSelectedIndex()==4 && convertido.getSelectedIndex()==0)
            Resultado.setText(String.valueOf(cantidad*0.13));
            if(convertir.getSelectedIndex()==4 && convertido.getSelectedIndex()==1)
            Resultado.setText(String.valueOf(cantidad*0.1152));
            if(convertir.getSelectedIndex()==4 && convertido.getSelectedIndex()==2)
            Resultado.setText(String.valueOf(cantidad*2.49));
            if(convertir.getSelectedIndex()==4 && convertido.getSelectedIndex()==3)
            Resultado.setText(String.valueOf(cantidad*3.19));
            if(convertir.getSelectedIndex()==4 && convertido.getSelectedIndex()==4)
            Resultado.setText(String.valueOf(cantidad*1));
            
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBorrarActionPerformed
        if(!Cantidad.getText().isEmpty() ||!Resultado.getText().isEmpty() ){
            Cantidad.setText("");
            Resultado.setText("");}
            else{
        if(Cantidad.getText().isEmpty() && Resultado.getText().isEmpty() )
            JOptionPane.showMessageDialog(null,"No hay datos para borrar");
        }
    }//GEN-LAST:event_jMenuBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor_Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor_Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor_Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor_Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor_Monedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abri_con;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Resultado;
    private javax.swing.JComboBox<String> convertido;
    private javax.swing.JComboBox<String> convertir;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBorrar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
